AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sample CloudFormation template'

Parameters:
  RecipientEmailAddresses:
    Type: String
    Description: 'Comma-separated list of email addresses'
    Default: 'Default'

  AccountName:
    Type: String
    Description: 'Name of this AWS account'
    Default: 'Default'

Resources:
  # CloudWatch Log Group for Lambda function
  IAMKeyRotationReportLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/IAMKeyRotationReport-${AWS::AccountId}'
      RetentionInDays: 14

  # IAM Role for Lambda function
  IAMKeyRotationReportRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  -
  -
  -
  -
  -
  -
  -
  -

Outputs:
  -
  -
  -